.

diff --git a/.github/workflows/cd-app-service-classic.yml b/.github/workflows/cd-app-service-classic.yml
--- a/.github/workflows/cd-app-service-classic.yml
+++ b/.github/workflows/cd-app-service-classic.yml
@@ -1,8 +1,6 @@
-name: cd-app-service-classic
+name: cd-app-service-classic-api
 
 on:
-  release:
-    types: [published]
   workflow_dispatch:
     inputs:
       version:
@@ -21,10 +19,7 @@ jobs:
         id: init
         run: |
           releaseVersion=""
-          if [[ "${{github.event_name}}" == "release" ]]; then
-            echo "Workflow started with on 'release' trigger"
-            releaseVersion="${GITHUB_REF#refs/*/}"
-          elif [[ "${{github.event_name}}" == "workflow_dispatch" ]]; then
+          if [[ "${{github.event_name}}" == "workflow_dispatch" ]]; then
             releaseVersion="${{inputs.version}}" 
           else
             echo "Unknown trigger: '${{github.event_name}}'"
@@ -46,12 +41,14 @@ jobs:
           echo "RELEASE_TYPE=${releaseType}" >> $GITHUB_OUTPUT
           echo "RELEASE_VERSION=${releaseVersion}" >> $GITHUB_OUTPUT
 
-  init_app_service_classic:
+  deploy_infra:
+    needs: [init]
     runs-on: ubuntu-latest
     environment: APP-SERVICE-CLASSIC
-    outputs:
-      ENVIRONMENT_DEPLOYED: ${{ steps.init.outputs.ENVIRONMENT_DEPLOYED }}    
+
     steps:
+      - uses: actions/checkout@v3
+
       - name: Azure login
         uses: azure/login@v1
         with:
@@ -60,82 +57,123 @@ jobs:
       - name: Set default Azure subscription
         run: az account set -s ${{secrets.AZURE_SUBSCRIPTION_ID}}
       
-      - name: Check environment exists
-        id: init
+      - name: Initialize deployment variables
+        id: vars
         run: |
-          RG_EXISTS=$(az group exists --name ${{secrets.AZURE_RESOURCE_GROUP}} --subscription ${{secrets.AZURE_SUBSCRIPTION_ID}})
-          if [[ "$RG_EXISTS" == "true" ]]; then
-            echo "ENVIRONMENT_DEPLOYED=true" >> $GITHUB_OUTPUT
-          else
-            echo "ENVIRONMENT_DEPLOYED=false" >> $GITHUB_OUTPUT
+          clientIP=`dig +short myip.opendns.com @resolver1.opendns.com.`
+          echo "DEPLOYMENT_CLIENT_IP=${clientIP}" >> $GITHUB_OUTPUT
+          echo "Client IP: $clientIP"
+
+          dbAdminName=`az postgres flexible-server list --query "[?fullyQualifiedDomainName == '${{secrets.AZURE_DB_SERVER_NAME}}.postgres.database.azure.com'].administratorLogin" -o tsv`
+          if [[ -z "$dbAdminName" ]]; then
+            echo "Unable to retrieve a DB admin name"
+            exit 1
+          fi
+          echo "Admin name: $dbAdminName"
+          echo "DB_ADMIN_NAME=${dbAdminName}" >> $GITHUB_OUTPUT
+          
+          dbAdminPassword=""
+          kvExists=`az keyvault list -g "${{secrets.AZURE_RESOURCE_GROUP}}" --query "[?name=='${{secrets.AZURE_KEY_VAULT_NAME}}'].name" -o tsv`
+          if [[ ! -z "$kvExists" ]]; then
+            kvSecretExists=`az keyvault secret list --vault-name ${{secrets.AZURE_KEY_VAULT_NAME}} --query "[?name=='DB-ADMIN-PASSWORD'].name" -o tsv`
+            if [[ ! -z "$kvSecretExists" ]]; then
+              dbAdminPassword=`az keyvault secret show --vault-name ${{secrets.AZURE_KEY_VAULT_NAME}} --name "DB-ADMIN-PASSWORD" --query "[value]" -o tsv`
+            fi
+          fi
+          if [[ -z "$dbAdminPassword" ]]; then
+            echo "Unable to retrieve a DB admin password"
+          fi
+          echo "Admin password: $dbAdminPassword"
+          echo "::add-mask::$dbAdminPassword"
+          echo "DB_ADMIN_PASSWORD=${dbAdminPassword}" >> $GITHUB_OUTPUT
+          
+          dbAppUserName=`echo "${{secrets.AZURE_API_APP_NAME}}" | tr '-' '_'`;
+          echo "DB_APP_USER_NAME=${dbAppUserName}" >> $GITHUB_OUTPUT
+          echo "App user name: $dbAppUserName"
+
+          dbStagingAppUserName=`echo "${{secrets.AZURE_API_APP_NAME}}-staging" | tr '-' '_'`;
+          echo "DB_STAGING_APP_USER_NAME=${dbStagingAppUserName}" >> $GITHUB_OUTPUT
+          echo "Staging app user name: $dbStagingAppUserName"
+
+          dbAppUserPassword=""
+          dbStagingAppUserPassword=""
+          kvExists=`az keyvault list -g "${{secrets.AZURE_RESOURCE_GROUP}}" --query "[?name=='${{secrets.AZURE_KEY_VAULT_NAME}}'].name" -o tsv`
+          if [[ ! -z "$kvExists" ]]; then
+            kvSecretExists=`az keyvault secret list --vault-name ${{secrets.AZURE_KEY_VAULT_NAME}} --query "[?name=='SPRING-DATASOURCE-PASSWORD'].name" -o tsv`
+            if [[ ! -z "$kvSecretExists" ]]; then
+              dbAppUserPassword=`az keyvault secret show --vault-name ${{secrets.AZURE_KEY_VAULT_NAME}} --name "SPRING-DATASOURCE-PASSWORD" --query "[value]" -o tsv`
+            fi
+            kvSecretExists=`az keyvault secret list --vault-name ${{secrets.AZURE_KEY_VAULT_NAME}} --query "[?name=='SPRING-DATASOURCE-PASSWORD-STAGING'].name" -o tsv`
+            if [[ ! -z "$kvSecretExists" ]]; then
+              dbStagingAppUserPassword=`az keyvault secret show --vault-name ${{secrets.AZURE_KEY_VAULT_NAME}} --name "SPRING-DATASOURCE-PASSWORD-STAGING" --query "[value]" -o tsv`
+            fi
+          fi
+          if [[ -z "$dbAppUserPassword" ]]; then
+            echo "Unable to retrieve a DB app user password"
+          fi
+          if [[ -z "$dbStagingAppUserPassword" ]]; then
+            echo "Unable to retrieve a DB staging app user password"
           fi
 
-  init_app_service_mi:
-    runs-on: ubuntu-latest
-    environment: APP-SERVICE-MI
-    outputs:
-      ENVIRONMENT_DEPLOYED: ${{ steps.init.outputs.ENVIRONMENT_DEPLOYED }}    
-    steps:
-      - name: Azure login
-        uses: azure/login@v1
-        with:
-          creds: ${{secrets.AZURE_CREDENTIALS}}
-      
-      - name: Set default Azure subscription
-        run: az account set -s ${{secrets.AZURE_SUBSCRIPTION_ID}}
-      
-      - name: Check environment exists
-        id: init
+          echo "DB_APP_USER_PASSWORD=${dbAppUserPassword}" >> $GITHUB_OUTPUT
+          echo "DB_STAGING_APP_USER_PASSWORD=${dbStagingAppUserPassword}" >> $GITHUB_OUTPUT
+
+      - name: Remove DB Firewall exception used for Schema sync
         run: |
-          RG_EXISTS=$(az group exists --name ${{secrets.AZURE_RESOURCE_GROUP}} --subscription ${{secrets.AZURE_SUBSCRIPTION_ID}})
-          if [[ "$RG_EXISTS" == "true" ]]; then
-            echo "ENVIRONMENT_DEPLOYED=true" >> $GITHUB_OUTPUT
-          else
-            echo "ENVIRONMENT_DEPLOYED=false" >> $GITHUB_OUTPUT
-          fi
-  
-  init_app_service_vnet:
-    runs-on: ubuntu-latest
-    environment: APP-SERVICE-VNET
-    outputs:
-      ENVIRONMENT_DEPLOYED: ${{ steps.init.outputs.ENVIRONMENT_DEPLOYED }}    
-    steps:
-      - name: Azure login
-        uses: azure/login@v1
-        with:
-          creds: ${{secrets.AZURE_CREDENTIALS}}
+          az postgres flexible-server firewall-rule add --rule-name "AllowDeploymentClientIP" --resource-group ${{secrets.AZURE_RESOURCE_GROUP}} --name ${{secrets.AZURE_DB_SERVER_NAME}} --yes
       
-      - name: Set default Azure subscription
-        run: az account set -s ${{secrets.AZURE_SUBSCRIPTION_ID}}
-      
-      - name: Check environment exists
-        id: init
+      - name: Synchronize DB Schema (NON AAD version)
         run: |
-          RG_EXISTS=$(az group exists --name ${{secrets.AZURE_RESOURCE_GROUP}} --subscription ${{secrets.AZURE_SUBSCRIPTION_ID}})
-          if [[ "$RG_EXISTS" == "true" ]]; then
-            echo "ENVIRONMENT_DEPLOYED=true" >> $GITHUB_OUTPUT
-          else
-            echo "ENVIRONMENT_DEPLOYED=false" >> $GITHUB_OUTPUT
-          fi  
-  
-  deploy_app_service_mi:
-    needs: [init, init_app_service_classic]
-    runs-on: ubuntu-latest
-    if: ${{contains(needs.init_app_service_classic.outputs.ENVIRONMENT_DEPLOYED, true)}}
-    environment: APP-SERVICE-MI
-    
-    steps:
-      - name: Azure login
-        uses: azure/login@v1
-        with:
-          creds: ${{secrets.AZURE_CREDENTIALS}}
-      
-      - name: Set default Azure subscription
-        run: az account set -s ${{secrets.AZURE_SUBSCRIPTION_ID}}
-      
-      - name: Test
+          dbConnectionString="host=${{secrets.AZURE_DB_SERVER_NAME}}.postgres.database.azure.com port=5432 dbname=${{secrets.AZURE_DB_NAME}} user=${{steps.vars.outputs.DB_ADMIN_NAME}} password=${{steps.vars.outputs.DB_ADMIN_PASSWORD}} sslmode=require"
+          psql "${dbConnectionString}" --file=./db.sql
+
+      - name: Check downloaded files
         run: |
-          echo "Running"
+          pwd
+          ls -la
+          ls -la ./${{needs.init.outputs.RELEASE_VERSIOB}}
+
+      - name: Start the STAGING slot
+        run: |
+          az webapp start -g ${{secrets.AZURE_RESOURCE_GROUP}} -n ${{secrets.AZURE_API_APP_NAME}} --slot staging
+
+      - name: Deploy to STAGING AppService
+        run: az webapp deploy -g ${{secrets.AZURE_RESOURCE_GROUP}} --name ${{secrets.AZURE_API_APP_NAME}} --slot staging --type jar --src-path ./${{needs.build_app.outputs.RELEASE_FILE_NAME}}
+
+      - name: Wait for STAGING AppService to restart and warm-up
+        run: |
+          ./scripts/warm_up.sh -u https://${{secrets.AZURE_API_APP_NAME}}-staging.azurewebsites.net/actuator/health/readiness
+
+      - name: Remove PROD AppService Liveness probe
+        run: |
+          az webapp config set -g ${{secrets.AZURE_RESOURCE_GROUP}} -n ${{secrets.AZURE_API_APP_NAME}} --generic-configurations '{"healthCheckPath": ""}'
+          sleep 180
+
+      - name: Swap STAGING and PRODUCTION
+        run:  |
+          az webapp deployment slot swap -g ${{secrets.AZURE_RESOURCE_GROUP}} --name ${{secrets.AZURE_API_APP_NAME}} --slot staging
+          sleep 180
+
+      - name: Wait for PROD AppService to restart and warm-up after the swap
+        run: |
+          ./scripts/warm_up.sh -u https://${{secrets.AZURE_API_APP_NAME}}.azurewebsites.net/actuator/health/readiness
+
+      - name: Set PRODUCTION AppService Liveness probe
+        run: |
+          currentDateTime=`date`
+          echo "Starting the probe set-up: ${currentDateTime}"
+          az webapp config set -g ${{secrets.AZURE_RESOURCE_GROUP}} -n ${{secrets.AZURE_API_APP_NAME}} --generic-configurations '{"healthCheckPath": "/actuator/health/liveness"}'
+          currentDateTime=`date`
+          echo "Finnished the probe set-up: ${currentDateTime}"
+
+      - name: Stop the STAGING slot
+        run: |
+          az webapp stop -g ${{secrets.AZURE_RESOURCE_GROUP}} -n ${{secrets.AZURE_API_APP_NAME}} --slot staging
+
+      - name: Remove DB Firewall exception used for Schema sync
+        run: |
+          az postgres flexible-server firewall-rule delete --rule-name "AllowDeploymentClientIP" --resource-group ${{secrets.AZURE_RESOURCE_GROUP}} --name ${{secrets.AZURE_DB_SERVER_NAME}} --yes
+      
       # - name: Download build artefacts
       #   uses: actions/download-artifact@v2
       #   with:
